formatter: markdown

output:
  file: README.md
  mode: replace
  template: |-

      # terraform-aws-iam-assume-role

      This module manage the AWS IAM to create role and policy to assume role.

      ## Usage

      ### Basic

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true